[postgres]
host = "coffee-bean-sales-mds-db-1"
port = 5432
database = "coffee_bean_sales"
username = "cbs_username"
password = "cbs_password"

[duckdb]
file_path = "../../sim_data_warehouse/sim_data_warehouse.duckdb"

[pipeline]
name = "postgres_to_duckdb"
dataset_name = "raw"

[tables]
source_tables = ["orders", "customers", "products"]

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
