name: 'transformation'
version: '1.0.0'
config-version: 2
profile: 'transformation'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transformation:
    staging:
      +schema: "staging"
      +materialized: table
    intermediate:
      +schema: "intermediate"
      +materialized: table
    marts:
      +schema: "marts"
      +materialized: table