transformation:
  target: trino
  outputs:
    trino:
      type: trino
      method: none
      host: localhost
      port: 8081
      user: dbt
      database: duckdb
      schema: marts
      threads: 4
    duckdb:
      type: duckdb
      path: '../sim_data_warehouse/sim_data_warehouse.duckdb'
      threads: 4